# version: '3'
services:
  app:
    build: .
    image: iotsrv
    container_name: iotsrv
    ports:
      - "8000:8000"
    depends_on:
      - mongo
#    environment:
#      - MONGO_URI=mongodb://mongo:27017/ #iotsrv
  mongo:
    image: mongo:7.0.14
#    ports:
#      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
